" This file is automatically generated by test-syntax from testing.vim

fun! Test_basic() abort
    call TestSyntax(g:test_packdir . '/test/basic.ditto',
        \ [
        \ [['dittoKeyword', 1, 7], ['dittoKeyword', 19, 26]],
        \ [],
        \ [['dittoKeyword', 1, 7]],
        \ [['dittoKeyword', 1, 7], ['dittoKeyword', 17, 19]],
        \ [],
        \ [['dittoKeyword', 1, 8]],
        \ [],
        \ [['dittoKeyword', 1, 5]],
        \ [],
        \ [['dittoKeyword', 1, 5]],
        \ [],
        \ [['dittoInt', 8, 9]],
        \ [['dittoFloat', 14, 17]],
        \ [['dittoFloat', 9, 12], ['dittoFloat', 14, 17]],
        \ [['dittoBool', 7, 11]],
        \ [['dittoBool', 6, 11]],
        \ [['dittoUnit', 8, 12]],
    \ ])
endfun
